export const pinAPITypes = {
  GET_ALL_PINS_SUCCESSFUL: "GET_ALL_PINS_SUCCESSFUL",
  GET_ALL_PINS_FAILED: "GET_ALL_PINS_FAILED",

  GET_PIN_NUMBER_SUCCESSFUL: "GET_PIN_NUMBER_SUCCESSFUL",
  GET_PIN_NUMBER_FAILED: "GET_PIN_NUMBER_FAILED",

  UPDATE_PIN_NUMBER_SUCCESSFUL: "UPDATE_PIN_NUMBER_SUCCESSFUL",
  UPDATE_PIN_NUMBER_FAILED: "UPDATE_PIN_NUMBER_FAILED",

  RESET_ALL_PIN_SUCCESSFUL: "RESET_ALL_PIN_SUCCESSFUL",
  RESET_ALL_PIN_FAILED: "RESET_ALL_PIN_FAILED"
};

export const userAPITypes = {
  LOGIN_SUCCESSFUL: "LOGIN_SUCCESSFUL",
  LOGIN_FAILED: "LOGIN_FAILED",

  GET_ALL_USERS_SUCCESSFUL: "GET_ALL_USERS_SUCCESSFUL",
  GET_ALL_USERS_FAILED: "GET_ALL_USERS_FAILED",

  CREATE_NEW_USER_SUCCESSFUL: "CREATE_NEW_USER_SUCCESSFUL",
  CREATE_NEW_USER_FAILED: "CREATE_NEW_USER_FAILED",

  GET_USER_INFO_SUCCESSFUL: "GET_USER_INFO_SUCCESSFUL",
  GET_USER_INFO_FAILED: "GET_USER_INFO_FAILED",

  GET_USER_BY_RFID_SUCCESSFUL: "GET_USER_BY_RFID_SUCCESSFUL",
  GET_USER_BY_RFID_FAILED: "GET_USER_BY_RFID_FAILED",

  UPDATE_USER_INFO_SUCCESSFUL: "UPDATE_USER_INFO_SUCCESSFUL",
  UPDATE_USER_INFO_FAILED: "UPDATE_USER_INFO_FAILED",

  DELETE_USER_SUCCESSFUL: "DELETE_USER_SUCCESSFUL",
  DELETE_USER_FAILED: "DELETE_USER_FAILED",

  DELETE_ALL_USERS_SUCCESSFUL: "DELETE_ALL_USERS_SUCCESSFUL",
  DELETE_ALL_USERS_FAILED: "DELETE_ALL_USERS_FAILED"
};

export const dhtAPITypes = {
  GET_ALL_DHT_DATA_SUCCESSFUL: "GET_ALL_DHT_DATA_SUCCESSFUL",
  GET_ALL_DHT_DATA_FAILED: "GET_ALL_DHT_DATA_FAILED",

  GET_LATEST_DHT_DATA_SUCCESSFUL: "GET_LATEST_DHT_DATA_SUCCESSFUL",
  GET_LATEST_DHT_DATA_FAILED: "GET_LATEST_DHT_DATA_FAILED",

  DELETE_ALL_DHT_DATA_SUCCESSFUL: "DELETE_ALL_DHT_DATA_SUCCESSFUL",
  DELETE_ALL_DHT_DATA_FAILED: "DELETE_ALL_DHT_DATA_FAILED"
};
