// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using System;
using Thesis.API.Context;

namespace Thesis.API.Migrations
{
    [DbContext(typeof(ThesisAPIContext))]
    [Migration("20181002125329_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026");

            modelBuilder.Entity("Thesis.API.Models.DHTModel.DHT", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("humidity")
                        .IsRequired();

                    b.Property<string>("key")
                        .IsRequired();

                    b.Property<string>("temperature")
                        .IsRequired();

                    b.HasKey("id");

                    b.ToTable("DHTs");
                });

            modelBuilder.Entity("Thesis.API.Models.PinModel.Pin", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("key")
                        .IsRequired();

                    b.Property<int>("pin");

                    b.Property<int>("state");

                    b.HasKey("id");

                    b.ToTable("Pins");
                });

            modelBuilder.Entity("Thesis.API.Models.UserModel.User", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("RFID")
                        .HasMaxLength(8);

                    b.Property<string>("name")
                        .HasMaxLength(20);

                    b.Property<string>("password")
                        .HasMaxLength(40);

                    b.Property<string>("role")
                        .HasMaxLength(10);

                    b.Property<string>("username")
                        .HasMaxLength(20);

                    b.HasKey("id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
